comment:
  glob-options:
    dot: true
  snippets:
    - id: preview-{{ id }}
      files: ["**/*"]
      body: |
        🧪 Preview is [ready]({{ url }})!
        <br>
        🖼️ Screenshots:
        | Chrome  | Firefox | Safari  |
        | ------- | ------- | ------- |
        | ![]({{ base }}/chrome-desktop-dark.webp)  | ![]({{ base }}/firefox-desktop-dark.webp)  | ![]({{ base }}/safari-desktop-dark.webp)  |
        | ![]({{ base }}/chrome-desktop-light.webp) | ![]({{ base }}/firefox-desktop-light.webp) | ![]({{ base }}/safari-desktop-light.webp) |
        | ![]({{ base }}/chrome-mobile-dark.webp)   | ![]({{ base }}/firefox-mobile-dark.webp)   | ![]({{ base }}/safari-mobile-dark.webp)   |
        | ![]({{ base }}/chrome-mobile-light.webp)  | ![]({{ base }}/firefox-mobile-light.webp)  | ![]({{ base }}/safari-mobile-light.webp)  |
