name: Deploy
on:
  push:
    branches:
      - deps/deno-deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: deno install

      - name: Build Astro
        run: deno task build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: tugrulates-www
          entrypoint: jsr:@std/http/file-server
          root: dist
