bug:
  - head-branch: ["^bug/", "^fix/", "^bugfix/"]

feature:
  - head-branch: ["^feat/", "^feature/", "^new/"]

dependencies:
  - head-branch: ["^dep/", "^deps/"]

documentation:
  - head-branch: ["^doc/", "^docs/", "^readme/"]

performance:
  - head-branch: ["^perf/", "^optimize/"]

refactor:
  - head-branch: ["^lint/", "^nit/", "^refactor/", "^tidy/"]

testing:
  - head-branch: ["^test/", "^testing/", "^tests/"]
