# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tugrul Ates
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
rss: rss

# Author
author:
  name: Tugrul Ates
  picture: /images/tugrulates.png
  email: me@tugrulates.com
  linkedin: tugrulates
  github: tugrulates
  stackoverflow: 634336/tugrul-ates
  twitter: turugula
  youtube: tugrulates
  instagram: turuling

# Links
permalink: :title
relative_links:
  collections: true

# Collections
collections:
  docs:
    output: true
    permalink: /:title
feed:
  path: _posts.atom
  collections:
    docs:
      path: "/feed.xml"

# Theme
markdown: kramdown
kramdown:
  footnote_backlink: "↵"
  math_engine: mathjax
theme: minima

# Titles
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Meta
defaults:
  -
    scope:
      path: ""
      type: "docs"
    values:
      state: 'draft'
      layout: post
      language: 'English'

# Plugins
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-titles-from-headings

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
