# Site
title: tugrul.blog
# TODO: #2 Write the site description
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tugrul.blog"
logo: "/assets/favicon.png"
states: public
show_excerpts: true

# Author
author:
  name: Tugrul Ates
  uri: https://tugrul.blog
  picture: /images/tugrulates.png
  linkedin: tugrulates
  github: tugrulates
  stackoverflow: 634336/tugrul-ates
  twitter: turugula
  youtube: tugrulates
  instagram: turuling

# Links
permalink: :title
relative_links:
  collections: true

# Collections
collections:
  docs:
    output: true
    permalink: /:path

# Feed
feed:
  template: _layouts/feed.atom
  path: /feed.atom
  tags:
    path: "/"

# Theme
markdown: kramdown
kramdown:
  footnote_backlink: "↵"
  math_engine: mathjax
theme: minima

# Titles
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Images
responsive_image:
  template: _includes/image.html
  sizes:
    - width: 40
    - width: 80
    - width: 120
    - width: 160
    - width: 320
    - width: 640
    - width: 960
    - width: 1280
  strip: true
  output_path_format: 'images/%{filename}-%{width}.%{extension}'
  save_to_source: false

# Meta
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      state: draft
      layout: post
      lang: en
      cover: "./images/roundest-object-on-earth.jpg"
  - scope:
      type: tags
    values:
      layout: home
      permalink: /:tag

# Plugins
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-responsive-image
  - jekyll-seo-tag
  - jekyll-tagories
  - jekyll-tidy
  - jekyll-titles-from-headings

# Files
exclude:
  - _docs/.*
  - scripts/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
