# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: tugrul.blog
tagline: Test
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tugrul.blog"
logo: "/assets/favicon.png"
rss: rss
show_excerpts: true

# Author
author:
  name: Tugrul Ates
  uri: https://www.tugrulates.com
  picture: /images/tugrulates.png
  email: me@tugrulates.com
  linkedin: tugrulates
  github: tugrulates
  stackoverflow: 634336/tugrul-ates
  twitter: turugula
  youtube: tugrulates
  instagram: turuling

# Social
social:
  name: Tugrul Ates
  links:
    - https://www.linkedin.com/in/tugrulates/
    - https://github.com/tugrulates
    - https://www.twitter.com/turugula
    - https://youtube.com/tugrulates
    - https://instagram.com/turuling

# Links
permalink: :title
relative_links:
  collections: true

# Collections
collections:
  docs:
    output: true
    permalink: /:path

# Feed
feed:
  template: _layouts/feed.atom
  path: /feed.atom

# Theme
markdown: kramdown
kramdown:
  footnote_backlink: "↵"
  math_engine: mathjax
theme: minima
minima:
  date_format: "%B %-d, %Y"

# Titles
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Images
responsive_image:
  template: _includes/srcset.html
  sizes:
    - width: 400
    - width: 800
  strip: true
  output_path_format: images/%{filename}-%{width}.%{extension}
  save_to_source: false
  extra_images:
    - _docs/images/*

# Meta
defaults:
  -
    scope:
      path: ""
      type: "docs"
    values:
      state: draft
      layout: post
      lang: en
      cover: "./images/roundest-object-on-earth.jpg"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-responsive-image
  - jekyll-seo-tag
  - jekyll-titles-from-headings

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
