base_url = "https://tugrul.blog"

title = "tugrul.blog"
description = "Let’s see where this goes."
default_language = "en"
# taxonomies = [{ name = "tags", feed = true }]
generate_feed = true
compile_sass = true
# trailing_slashes = false

[markdown]
highlight_code = true
highlight_theme = "css"
external_links_target_blank = true

[slugify]
paths = "on"
taxonomies = "off"
anchors = "on"

[link_checker]
skip_prefixes = [
    "https://www.linkedin.com/",
]

[extra.author]
name = "Tugrul Ates"
picture = "/png/me.png"
linkedin = "tugrulates"
github = "tugrulates"
stackoverflow = "634336/tugrul-ates"
twitter = "turugula"
youtube = "tugrulates"

[extra.content]
greeting = "Hello, I’m Tugrul!"
