[build]
  publish = "public/"
  command = "npm run build -- --drafts"

[[plugins]]
package = "netlify-plugin-csp-generator"
  [plugins.inputs]
  buildDir = "public"
  disableGeneratedPolicies = ["styleSrc"]
  [plugins.inputs.policies]
    scriptSrc = "'self' 'unsafe-hashes' 'sha256-JBhAzDOM5zUvFs5wf3KR6W1uAcXAi9aUaaHIyfL6nVQ=' 'sha256-YCI1+jSo7EVM0oHgxtxB82JSp+59HeM97qAuRzm/+88='"
    styleSrc = "'self' 'unsafe-inline'"
    frameSrc = "'self' https://www.youtube.com"
    objectSrc = "'none'"
    base-uri = "'none'"
    defaultSrc = "'self'"

[[redirects]]
  from = "https://tugrul.netlify.app/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.com/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.com/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.net/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.net/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.org/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.org/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true

## TODO: #45 Remove files redirect sometime in 2023
[[redirects]]
  from = "/files/*"
  to = "/:splat"
  status = 301
  force = true
