[build]
  publish = "public/"
  command = "zola build"

[context.drafts]
  command = "zola build --drafts"

[dev]
  framework = "#custom"
  command = "zola serve --drafts --port 1111"
  targetPort = 1111
  port = 1001
  autoLaunch = false

[context.test]
  command = "echo Running checks"
  [[context.test.plugins]]
    package = "netlify-plugin-checklinks"
    [context.test.plugins.inputs]
      entryPoints = [ "*.html", "**.html", ]
      recursive = true
      pretty = true
      checkExternal = false
  [[context.test.plugins]]
    package = "netlify-plugin-chromium"
  [[context.test.plugins]]
    package = "netlify-plugin-html-validate"
    [context.test.plugins.inputs]
      path = "public"
      config = ".htmlvalidate.json"
  [[context.snyk.plugins]]
    package = "netlify-plugin-is-website-vulnerable"

[context.lighthouse-desktop]
  command = "echo Running Lighthouse for desktop"
  [[context.lighthouse-desktop.plugins]]
    package = "@netlify/plugin-lighthouse"
    [context.lighthouse-desktop.plugins.inputs.settings]
      preset = "desktop"
    [context.lighthouse-desktop.plugins.inputs.thresholds]
      performance = 0.9
      accessibility = 1
      best-practices = 1
      seo = 1
    [[context.lighthouse-desktop.plugins.inputs.audits]]
      output_path = "../lighthouse/desktop-home.html"
    [[context.lighthouse-desktop.plugins.inputs.audits]]
      path = "research/"
      output_path = "../lighthouse/desktop-page.html"

[context.lighthouse-mobile]
  command = "echo Running Lighthouse for mobile"
  [[context.lighthouse-mobile.plugins]]
    package = "@netlify/plugin-lighthouse"
    [context.lighthouse-mobile.plugins.inputs.thresholds]
      performance = 0.9
      accessibility = 1
      best-practices = 1
      seo = 1
    [[context.lighthouse-mobile.plugins.inputs.audits]]
      output_path = "../lighthouse/mobile-home.html"
    [[context.lighthouse-mobile.plugins.inputs.audits]]
      path = "research/"
      output_path = "../lighthouse/mobile-page.html"

[[redirects]]
  from = "https://tugrul.netlify.app/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.com/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.com/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.net/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.net/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.org/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.org/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true

## TODO: #45 Remove files redirect sometime in 2023
[[redirects]]
  from = "/files/*"
  to = "/:splat"
  status = 301
  force = true
