[build]
  publish = "public"
  command = "npm run build"

[context.drafts]
  command = "npm run build -- --drafts"

[context.local]
  command = "zola build --drafts"
  [[context.local.plugins]]
  package = "netlify-plugin-csp-generator"
    [context.local.plugins.inputs.policies]
      connectSrc = "*"

[dev]
  framework = "#custom"
  command = "zola serve --drafts --port 1111"
  targetPort = 1111
  port = 1001
  autoLaunch = false

[[plugins]]
  package = "netlify-plugin-csp-generator"
    [plugins.inputs]
      buildDir = "public"
      # Need unsafe inline style and the following two SHA for mermaid.js to work (#11).
      # No need to disable style hashes if a stricter policy is set.
      disableGeneratedPolicies = ["styleSrc"]
      [plugins.inputs.policies]
        scriptSrc = "'self' 'unsafe-inline' 'unsafe-hashes' 'sha256-1CldwzdEg2k1wTmf7s5RWVd7NMXI/7nxxjJM2C4DqII=' 'sha256-YCI1+jSo7EVM0oHgxtxB82JSp+59HeM97qAuRzm/+88='"
        styleSrc = "'self' 'unsafe-inline'"
        frameSrc = "'self' https://www.youtube.com"
        imgSrc = "'self'"
        manifestSrc = "'self'"
        frameAncestors = "'none'"
        formAction = "'none'"
        baseUri = "'none'"
        defaultSrc = "'none'"

[[plugins]]
  package = "netlify-plugin-html-validate"
  [plugins.inputs]
    path = "public"
    config = ".htmlvalidate.json"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 1
    best-practices = 1
    seo = 1
  [[plugins.inputs.audits]]
    output_path = "lighthouse/home.html"
  [[plugins.inputs.audits]]
    path = "research/"
    output_path = "lighthouse/page.html"

[[headers]]
  for = "/*"
  [headers.values]
    # Blocks safari webdriver, evaluate after #92
    # Cross-Origin-Embedder-Policy = "require-corp"
    # Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=*, geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), speaker-selection=(), conversion-measurement=(), focus-without-user-activation=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), sync-script=(), trust-token-redemption=(), unload=(), window-placement=(), vertical-scroll=()"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

[[redirects]]
  from = "https://tugrul.netlify.app/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.com/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.com/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.net/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.net/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.org/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.org/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
