[build]
  publish = "public/"
  command = "zola build"

[context.drafts]
  command = "zola build --drafts"

[dev]
  publish = "public/"
  framework = "#custom"
  command = "zola serve --drafts --port 1111"
  targetPort = 1111
  port = 1001
  autoLaunch = false

[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
  entryPoints = [ "*.html", "**.html", ]
  recursive = true
  pretty = true
  checkExternal = false
[[plugins]]
  package = "netlify-plugin-html-validate"
  [plugins.inputs]
    path = "public"
    config = ".htmlvalidate.json"
[[plugins]]
  package = "netlify-plugin-is-website-vulnerable"

[[redirects]]
  from = "https://tugrul.netlify.app/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.com/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.com/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.net/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.net/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.org/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.org/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true

## TODO: #45 Remove files redirect sometime in 2023
[[redirects]]
  from = "/files/*"
  to = "/:splat"
  status = 301
  force = true
