[build]
  publish = "public/"
  command = "zola build"

[context.drafts]
  command = "zola build --drafts"

[context.local]
  command = "zola build --drafts"
  [[context.local.plugins]]
  package = "netlify-plugin-csp-generator"
    [context.local.plugins.inputs.policies]
      connectSrc = "*"

[dev]
  framework = "#custom"
  command = "zola serve --drafts --port 1111"
  targetPort = 1111
  port = 1001
  autoLaunch = false

[[plugins]]
  package = "netlify-plugin-csp-generator"
    [plugins.inputs]
      buildDir = "public"
      # Need unsafe inline style and the following two SHA for mermaid.js to work (#11).
      # No need to disable style hashes if a stricter policy is set.
      disableGeneratedPolicies = ["styleSrc"]
      [plugins.inputs.policies]
        scriptSrc = "'self' 'unsafe-inline' 'unsafe-hashes' 'sha256-JBhAzDOM5zUvFs5wf3KR6W1uAcXAi9aUaaHIyfL6nVQ=' 'sha256-YCI1+jSo7EVM0oHgxtxB82JSp+59HeM97qAuRzm/+88='"
        styleSrc = "'self' 'unsafe-inline'"
        frameSrc = "'self' https://www.youtube.com"
        imgSrc = "'self'"
        manifestSrc = "'self'"
        frameAncestors = "'none'"
        formAction = "'none'"
        baseUri = "'none'"
        defaultSrc = "'none'"

[[headers]]
  for = "/*"
  [headers.values]
    # Blocks safari webdriver, evaluate after #92
    # Cross-Origin-Embedder-Policy = "require-corp"
    # Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=*, geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), speaker-selection=(), conversion-measurement=(), focus-without-user-activation=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), sync-script=(), trust-token-redemption=(), unload=(), window-placement=(), vertical-scroll=()"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

[context.test]
  command = "echo Running checks"
  [[context.test.plugins]]
    package = "netlify-plugin-checklinks"
    [context.test.plugins.inputs]
      entryPoints = [ "*.html", "**.html", ]
      recursive = true
      pretty = true
      checkExternal = false
  [[context.test.plugins]]
    package = "netlify-plugin-chromium"
  [[context.test.plugins]]
    package = "netlify-plugin-html-validate"
    [context.test.plugins.inputs]
      path = "public"
      config = ".htmlvalidate.json"
  # TODO: #138 Add back vulnurability checks
  # [[context.test.plugins]]
  #   package = "netlify-plugin-is-website-vulnerable"

[context.lighthouse-desktop]
  command = "echo Running Lighthouse for desktop"
  [[context.lighthouse-desktop.plugins]]
    package = "@netlify/plugin-lighthouse"
    [context.lighthouse-desktop.plugins.inputs.settings]
      preset = "desktop"
    [context.lighthouse-desktop.plugins.inputs.thresholds]
      performance = 0.9
      accessibility = 1
      best-practices = 1
      seo = 1
    [[context.lighthouse-desktop.plugins.inputs.audits]]
      output_path = "../lighthouse/desktop-home.html"
    [[context.lighthouse-desktop.plugins.inputs.audits]]
      path = "research/"
      output_path = "../lighthouse/desktop-page.html"

[context.lighthouse-mobile]
  command = "echo Running Lighthouse for mobile"
  [[context.lighthouse-mobile.plugins]]
    package = "@netlify/plugin-lighthouse"
    [context.lighthouse-mobile.plugins.inputs.thresholds]
      performance = 0.9
      accessibility = 1
      best-practices = 1
      seo = 1
    [[context.lighthouse-mobile.plugins.inputs.audits]]
      output_path = "../lighthouse/mobile-home.html"
    [[context.lighthouse-mobile.plugins.inputs.audits]]
      path = "research/"
      output_path = "../lighthouse/mobile-page.html"

[[redirects]]
  from = "https://tugrul.netlify.app/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.com/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.com/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.net/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.net/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://tugrulates.org/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.tugrulates.org/*"
  to = "https://tugrul.blog/:splat"
  status = 301
  force = true
