name: CI

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      update_docs:
        required: false
        type: boolean
      build_args:
        required: false
        type: string
      deploy_args:
        required: false
        type: string
    outputs:
      url:
        description: "URL for deployed site"
        value: ${{ jobs.deploy.outputs.url }}

jobs:
  container:
    uses: ./.github/workflows/container.yml
    with:
      latest: ${{ inputs.environment == 'live' }}

  build:
    needs: container
    uses: ./.github/workflows/build.yml
    with:
      container: ${{ needs.container.outputs.container }}
      update_docs: ${{ inputs.update_docs }}
      build_args: ${{ inputs.build_args }}

  test:
    needs: [container, build]
    uses: ./.github/workflows/test.yml
    with:
      container: ${{ needs.container.outputs.container }}
      artifact: ${{ needs.build.outputs.artifact }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ inputs.environment }}
      artifact: ${{ needs.build.outputs.artifact }}
      deploy_args: ${{ inputs.deploy_args }}
    secrets: inherit

  e2e:
    needs: deploy
    uses: ./.github/workflows/e2e.yml
    with:
      url: ${{ needs.deploy.outputs.url }}
      environment: ${{ inputs.environment }}
    secrets: inherit
