name: CI

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      update_docs:
        required: false
        type: boolean
      deploy_args:
        required: false
        type: string
    outputs:
      url:
        description: "URL for deployed site"
        value: ${{ jobs.deploy.outputs.url }}

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
    with:
      latest: ${{ inputs.environment == 'live' }}

  deploy:
    needs: prepare
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ inputs.environment }}
      container: ${{ needs.prepare.outputs.container }}
      update_docs: ${{ inputs.update_docs }}
      deploy_args: ${{ inputs.deploy_args }}
    secrets: inherit

  e2e:
    needs: deploy
    uses: ./.github/workflows/e2e.yml
    with:
      url: ${{ needs.deploy.outputs.url }}
      environment: ${{ inputs.environment }}
    secrets: inherit
