name: CI

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      container:
        required: false
        type: string
        default: ghcr.io/tugrulates/blog-devcontainer:main
      update_docs:
        required: false
        type: string
      build_args:
        required: false
        type: string
      deploy_args:
        required: false
        type: string
    secrets:
      NETLIFY_SITE_ID:
        required: true
      NETLIFY_AUTH_TOKEN:
        required: true
      LHCI_GITHUB_TOKEN:
        required: true
    outputs:
      url:
        description: "URL for deployed site"
        value: ${{ jobs.deploy.outputs.url }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      container: ${{ inputs.container }}
      update_docs: true
      build_args: ${{ inputs.build_args }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ inputs.environment }}
      artifact: ${{ needs.build.outputs.artifact }}
      deploy_args: ${{ inputs.deploy_args }}
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  test:
    needs: [build, deploy]
    uses: ./.github/workflows/test.yml
    with:
      container: ${{ inputs.container }}
      artifact: ${{ needs.build.outputs.artifact }}
      url: ${{ needs.deploy.outputs.url }}
      lhci_config: tests/lighthouserc.${{ inputs.environment }}.js
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
