name: CI

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      update_docs:
        required: false
        type: string
      build_args:
        required: false
        type: string
      deploy_args:
        required: false
        type: string
    outputs:
      url:
        description: "URL for deployed site"
        value: ${{ jobs.deploy.outputs.url }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      latest: ${{ inputs.environment == 'live' }}
      update_docs: true
      build_args: ${{ inputs.build_args }}

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    with:
      container: ${{ needs.build.outputs.container }}
      artifact: ${{ needs.build.outputs.artifact }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ inputs.environment }}
      artifact: ${{ needs.build.outputs.artifact }}
      deploy_args: ${{ inputs.deploy_args }}
    secrets: inherit

  e2e:
    needs: deploy
    uses: ./.github/workflows/e2e.yml
    with:
      url: ${{ needs.deploy.outputs.url }}
      environment: ${{ inputs.environment }}
    secrets: inherit
