name: Build

on:
  workflow_call:
    inputs:
      latest:
        required: false
        type: boolean
    outputs:
      container:
        description: "Container tag"
        value: ${{ jobs.container.outputs.container }}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/blog-devcontainer

jobs:
  container:
    outputs:
      container: ${{ steps.name.outputs.container }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: "${{ github.token }}"

      - name: Container metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=tugrul-blog-devcontainer
            org.opencontainers.image.description=Devcontainer for building tugrul.blog
          flavor: latest=${{ inputs.latest }}
          sep-tags: ","

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check diff
        id: name
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          git fetch origin main
          if ${{ github.event_name == 'push' }} || git diff origin/main --name-only .devcontainer
          then
            echo "container=${TAGS##*,}" >> ${GITHUB_OUTPUT}
            echo "build=true" >> ${GITHUB_OUTPUT}
          else
            echo "container=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> ${GITHUB_OUTPUT}
          fi

      - name: Build and Push
        if: ${{ steps.name.outputs.build }}
        uses: docker/build-push-action@v3
        with:
          context: "{{ defaultContext }}:.devcontainer"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: ${{ steps.name.outputs.tag }}
          cache-to: type=inline
