name: Deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    outputs:
      preview_url: ${{ steps.preview.outputs.preview_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup env
        if: github.event_name == 'pull_request'
        run: |
          echo "DEPLOY_ARGS=--context=deploy-preview" >> $GITHUB_ENV
      - name: Setup env
        if: github.event_name == 'push'
        run: |
          echo "DEPLOY_ARGS=--prod" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
      - name: Install dependencies
        run: |
          npm install
          sudo apt-get install graphicsmagick
          wget -q -O - "https://github.com/getzola/zola/releases/download/v0.15.3/zola-v0.15.3-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C /usr/local/bin
      - name: Deploy preview
        id: preview
        run: |
          OUTPUT=$(mktemp)
          npx netlify deploy --build --dir=public $DEPLOY_ARGS | tee $OUTPUT
          PREVIEW_URL=$(grep -oP '(?<=(?:Website Draft|Unique Deploy) URL: )((.*))' $OUTPUT)
          DEPLOY_ID=$(echo $PREVIEW_URL | grep -oP '(?<=https://)((.*))((?=--))')
          echo "::set-output name=preview_url::$PREVIEW_URL"
          echo "::set-output name=deploy_id::$DEPLOY_ID"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: exercism/pr-commenter-action@v1.3.0
        with:
          github-token: "${{ github.token }}"
          config-file: ".github/preview-url-comment.yml"
          template-variables: |
            {
              "preview_url": "${{ steps.preview.outputs.preview_url }}",
              "deploy_id":   "${{ steps.preview.outputs.deploy_id }}"
            }
