name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      artifact:
        required: true
        type: string
      deploy_args:
        required: false
        type: string
    outputs:
      url:
        description: "URL for deployed site"
        value: ${{ jobs.deploy.outputs.url }}

env:
  OUTPUT_DIR: public

jobs:
  deploy:
    name: Deploy blog
    outputs:
      url: ${{ steps.publish.outputs.url }}
    environment:
      name: ${{ inputs.environment}}
      url: ${{ steps.publish.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: ${{ env.OUTPUT_DIR }}

      - name: Publish
        id: publish
        run: |
          OUTPUT=$(mktemp)
          netlify deploy --json --message "Deploy from ${{ github.ref_name }}" \
            --dir=${{ env.OUTPUT_DIR }} ${{ inputs.deploy_args }} | tee ${OUTPUT}
          echo "url=$(jq -r '.url,.deploy_url' $OUTPUT | grep https | head -n 1)" >> ${GITHUB_OUTPUT}
          echo "deploy_id=$(jq -r '.deploy_id' $OUTPUT)" >> ${GITHUB_OUTPUT}
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: exercism/pr-commenter-action@v1.3.0
        with:
          github-token: "${{ github.token }}"
          config-file: ".github/comment-preview.yml"
          template-variables: |
            {
              "id":  "${{ steps.publish.outputs.deploy_id }}",
              "url": "${{ steps.publish.outputs.url }}"
            }
