name: Deploy

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    outputs:
      preview_url: ${{ steps.preview.outputs.preview_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
      - name: Deploy preview
        id: preview
        run: |
          OUTPUT=$(mktemp)
          netlify deploy --build --dir=_site --context=deploy-preview | tee $OUTPUT
          PREVIEW_URL=$(grep -oP '(?<=Website Draft URL: )((.*))' $OUTPUT)
          DEPLOY_ID=$(echo $PREVIEW_URL | grep -oP '(?<=https://)((.*))((?=--))')
          echo "::set-output name=preview_url::$PREVIEW_URL"
          echo "::set-output name=deploy_id::$DEPLOY_ID"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Comment on PR
        uses: exercism/pr-commenter-action@v1.3.0
        with:
          github-token: "${{ github.token }}"
          config-file: ".github/preview-url-comment.yml"
          template-variables: |
            {
              "preview_url": "${{ steps.preview.outputs.preview_url }}",
              "deploy_id":   "${{ steps.preview.outputs.deploy_id }}"
            }
