name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      artifact:
        required: true
        type: string
    secrets:
      NETLIFY_SITE_ID:
        required: true
      NETLIFY_AUTH_TOKEN:
        required: true
    outputs:
      url:
        description: "URL for deployed site"
        value: ${{ jobs.deploy.outputs.url }}

env:
  OUTPUT_DIR: public
  PROD_DEPLOY_ARGS: --prod

jobs:
  deploy:
    name: Deploy blog
    outputs:
      deploy_id: ${{ steps.publish.outputs.deploy_id }}
      url: ${{ steps.publish.outputs.url }}
    environment:
      name: ${{ inputs.environment}}
      url: ${{ steps.publish.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: ${{ env.OUTPUT_DIR }}

      - name: Setup args
        id: args
        if: inputs.environment == 'production'
        run: echo "deploy_args=${{ env.PROD_DEPLOY_ARGS }}" >> ${GITHUB_OUTPUT}

      - name: Publish
        id: publish
        run: |
          OUTPUT=$(mktemp)
          netlify deploy --message "${{ github.ref_name }}" --dir=${{ env.OUTPUT_DIR }} ${{ steps.args.outputs.deploy_args }} | tee ${OUTPUT}
          URL=$(cat ${OUTPUT} | grep -E "Website.*URL:" | grep "http.*" -o)
          DEPLOY_ID=$(grep -E 'Logs:' ${OUTPUT} | grep '[^/]*$' -o)
          echo "url=${URL}" >> ${GITHUB_OUTPUT}
          echo "deploy_id=${DEPLOY_ID}" >> ${GITHUB_OUTPUT}
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: exercism/pr-commenter-action@v1.3.0
        with:
          github-token: "${{ github.token }}"
          config-file: ".github/comment-preview.yml"
          template-variables: |
            {
              "id":  "${{ steps.publish.output.deploy_id }}",
              "url": "${{ steps.publish.outputs.url }}"
            }
