name: Deploy
on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Deploy redirect
        uses: denoland/deployctl@v1
        with:
          project: "trl-redirect"
          root: "src"
          entrypoint: "scripts/serve-redirect.ts"
          import-map: "deno.json"

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install
        run: "deno install"

      - name: Build
        run: "deno task build"

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: "trl"
          root: "dist"
          entrypoint: "server/entry.mjs"

