name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      container:
        required: true
        type: string
      update_docs:
        required: false
        type: boolean
      deploy_args:
        required: false
        type: string
    outputs:
      url:
        description: "URL for deployed site"
        value: ${{ jobs.deploy.outputs.url }}

jobs:
  deploy:
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    environment:
      name: ${{ inputs.environment}}
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup permissions
        run: sudo chown $(whoami) .
      - name: Update docs
        if: ${{ inputs.update_docs }}
        run: git submodule update --init --recursive --remote docs
      - name: Install node dependencies
        run: npm ci
      - name: Deploy
        id: deploy
        run: |
          which netlify
          netlify --telemetry-disable deploy --build -context ${{ inputs.environment }} --message ${{ github.ref_name }} ${{ inputs.deploy_args }}
          OUTPUT=$(mktemp)
          npm run deploy -- --context ${{ inputs.environment }} --message ${{ github.ref_name }} ${{ inputs.deploy_args }}
          cat $OUTPUT
          echo "url=$(jq -r '.url,.deploy_url' $OUTPUT | grep https | head -n 1)" >> ${GITHUB_OUTPUT}
          echo "deploy_id=$(jq -r '.deploy_id' $OUTPUT)" >> ${GITHUB_OUTPUT}
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: exercism/pr-commenter-action@v1.3.0
        with:
          github-token: "${{ github.token }}"
          config-file: ".github/comment-preview.yml"
          template-variables: |
            {
              "id":  "${{ steps.deploy.outputs.deploy_id }}",
              "url": "${{ steps.deploy.outputs.url }}"
            }
