name: Deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    outputs:
      preview_url: ${{ steps.preview.outputs.preview_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"
      - name: Install dependencies
        run: |
          npm install
          sudo apt-get install graphicsmagick
          wget -q -O - "https://github.com/getzola/zola/releases/download/v0.15.3/zola-v0.15.3-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C /usr/local/bin
      - name: Deploy preview
        id: preview
        run: |
          OUTPUT=$(mktemp)
          npx netlify deploy --build --dir=public --context=deploy-preview | tee $OUTPUT
          PREVIEW_URL=$(grep -oP '(?<=(?:Website Draft|Unique Deploy) URL: )((.*))' $OUTPUT)
          DEPLOY_ID=$(echo $PREVIEW_URL | grep -oP '(?<=https://)((.*))((?=--))')
          echo "::set-output name=preview_url::$PREVIEW_URL"
          echo "::set-output name=deploy_id::$DEPLOY_ID"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: exercism/pr-commenter-action@v1.3.0
        with:
          github-token: "${{ github.token }}"
          config-file: ".github/preview-url-comment.yml"
          template-variables: |
            {
              "preview_url": "${{ steps.preview.outputs.preview_url }}",
              "deploy_id":   "${{ steps.preview.outputs.deploy_id }}"
            }
      # - name: Deploy to production
      #   if: github.event_name == 'push'
      #   run: npx netlify deploy --dir=public --prod

  screenshot-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install selenium
        run: |
          pip3 install selenium
          pip3 install --upgrade requests
      - name: Install geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux32.tar.gz
          tar -xvzf geckodriver*
          chmod +x geckodriver
          export PATH=$PATH:./geckodriver
      - name: Run selenium
        run: python3 tests/screenshot.py --browser=firefox --out=linux-firefox.png
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Linux Firefox
          path: "linux-firefox.png"
          retention-days: 1

  screenshot-linux:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install selenium
        run: |
          pip3 install selenium
          pip3 install --upgrade requests
      - name: Run selenium
        run: python3 tests/screenshot.py --browser=firefox --out=macos-safari.png
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MacOS Safari
          path: "macos-safari.png"
          retention-days: 1
