name: Jekyll build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Debug github context
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.head_ref }}
          echo ${{ github.ref }}
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: tugrulates/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pre_build_commands: apk --update add imagemagick imagemagick-c++ imagemagick-dev imagemagick-libs
          target_branch: 'gh-pages'
