name: Jekyll build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      path: ${{ steps.path.outputs.path }}
    steps:
      - id: path
        name: Determine output path
        run: bash -c '[[ "(${{ github.ref_name }}" = "main" ]] && echo "::set-output name=path::/") || (([[ -z "${{ github.head_ref }}" ]] && echo "::set-output name=path::/branch/${{ github.ref_name }}") || echo "::set-output name=path::/branch/${{ github.head_ref }}")'
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Update base url
        run: echo "${{ format('baseurl{0}', ':') }} ${{ steps.path.outputs.path }}" >> _config.yml
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: tugrulates/jekyll-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pre_build_commands: apk --update add imagemagick imagemagick-c++ imagemagick-dev imagemagick-libs
          target_path: ${{ steps.path.outputs.path }}
          keep_history: ${{ steps.path.outputs.path != '/' }}
          target_branch: 'gh-pages'
