name: Labeler
on: [pull_request_target, workflow_dispatch]

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
