name: Pull Request (Container Change)

on:
  pull_request:
    branches:
      - main
    paths:
      - ".devcontainer/**"
  workflow_dispatch:

jobs:
  container:
    uses: ./.github/workflows/container.yml

  integrate:
    needs: container
    uses: ./.github/workflows/integrate.yml
    with:
      environment: development
      container: ${{ needs.container.outputs.container }}
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
