name: On Pull Request

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  container:
    uses: ./.github/workflows/container.yml

  preview:
    needs: container
    uses: ./.github/workflows/ci.yml
    with:
      environment: preview
      container: ${{ needs.container.outputs.container }}
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
