name: Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - "**"
      - "!.devcontainer/**"
  workflow_dispatch:

jobs:
  integrate:
    uses: ./.github/workflows/integrate.yml
    with:
      environment: development
      container: ghcr.io/tugrulates/blog-devcontainer:main
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
