name: On Push

on:
  push:
    branches: [main]

concurrency: live

jobs:
  preview:
    uses: ./.github/workflows/ci.yml
    with:
      environment: preview
    secrets: inherit

  live:
    needs: preview
    uses: ./.github/workflows/ci.yml
    with:
      environment: live
    secrets: inherit
