name: Prune

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  USERNAME: tugrulates
  CONTAINER: blog-devcontainer
  MAX_AGE_DAYS: 7

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CR_TOKEN }}
          script: |
            await github.rest.packages
              .getAllPackageVersionsForPackageOwnedByUser({
                package_type: "container",
                username: "${{ env.USERNAME }}",
                package_name: "${{ env.CONTAINER }}",
              })
              .then(
                async ({ data }) =>
                  await Promise.all(
                    data
                      .filter((version) => {
                        const msPerDay = 24 * 60 * 60 * 1000;
                        const age = (new Date() - new Date(version.created_at)) / msPerDay;
                        const tags = version.metadata?.container?.tags ?? [];
                        return (
                          age > ${{ env.MAX_AGE_DAYS }} &&
                          tags.filter((tag) => tag.match(/^pr-\d+$/) == null).length === 0
                        );
                      })
                      .map(
                        async (version) =>
                          await github.rest.packages.deletePackageVersionForUser({
                            package_type: "container",
                            username: "${{ env.USERNAME }}",
                            package_name: "${{ env.CONTAINER }}",
                            package_version_id: version.id,
                          })
                      )
                  )
              )
