name: Publish

on:
  workflow_dispatch:
  repository_dispatch:
    types: [Publish]

concurrency: drafts

jobs:
  publish:
    uses: ./.github/workflows/ci.yml
    with:
      environment: drafts
      update_docs: true
      build_args: --drafts
      deploy_args: --alias drafts
    secrets: inherit

  update:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BLOG_PUBLISH_TOKEN }}
      - name: Create update commit
        run: |
          git submodule update --init --recursive --remote docs
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add docs
          git commit -m "Update docs" && git push || echo "No changes to commit"
          git push
