name: Pull Request

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  preview:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      environment: preview

  comment:
    needs: preview
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: reports
          path: reports
      - name: Deploy
        run: npm run -s deploy -- --message reports --dir=reports --json > deploy.json
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Get JSON
        id: json
        run: echo json=$(cat deploy.json) >> ${GITHUB_OUTPUT}
      - uses: exercism/pr-commenter-action@v1.4.0
        with:
          github-token: "${{ secrets.PR_COMMENT_TOKEN }}"
          template-variables: |
            {
              "id":        "${{ fromJSON(steps.json.outputs.json).deploy_id }}",
              "reports":   "${{ fromJSON(steps.json.outputs.json).deploy_url }}",
              "result":    "${{ needs.preview.result }}",
              "preview":   "${{ needs.preview.outputs.url }}",
              "lighthouse": ${{ needs.preview.outputs.url }}
            }
