name: Pull Request

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  preview:
    uses: ./.github/workflows/ci.yml
    with:
      environment: preview
      container: ghcr.io/tugrulates/blog-devcontainer:latest
    secrets: inherit
