name: Push

on:
  push:
    branches: [main]

concurrency: live

jobs:
  preview:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      environment: preview

  live:
    needs: preview
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    with:
      environment: live
      latest: true
      deploy_args: --prod
