name: Test

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
      lhci_config:
        required: false
        type: string
        default: tests/lighthouserc.js
    secrets:
      LHCI_GITHUB_TOKEN:
        required: true
      NETLIFY_SITE_ID:
        required: true
      NETLIFY_AUTH_TOKEN:
        required: true

jobs:
  lighthouse:
    name: Lighthouse
    strategy:
      matrix:
        form: [desktop, mobile]
        url: ["/", "/research/"]
        include:
          - form: desktop
            preset: --collect.settings.preset=desktop
          - form: mobile
            preset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Lighthouse
        run: npm install && npm install -g @lhci/cli@0.9.x
      - name: Run Lighthouse
        run: lhci autorun ${{ inputs.lhci_args }} ${{ matrix.preset }} --collect.url="${{ inputs.url }}${{ matrix.url }}"
        env:
          LHCI_CONFIG: ${{ inputs.lhci_config }}
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}

  screenshot:
    uses: ./.github/workflows/screenshot.yml
    with:
      url: ${{ inputs.url }}
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
