name: Test

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
    secrets:
      NETLIFY_SITE_ID:
        required: true
      NETLIFY_AUTH_TOKEN:
        required: true

jobs:
  screenshot:
    uses: ./.github/workflows/screenshot.yml
    with:
      url: ${{ inputs.url }}
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
