name: Test (Local)

on:
  workflow_call:
    inputs:
      container:
        required: true
        type: string
      artifact:
        required: true
        type: string

env:
  OUTPUT_DIR: public

jobs:
  local:
    name: Local tests
    runs-on: ubuntu-latest
    container: ${{ inputs.container }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
          path: ${{ env.OUTPUT_DIR }}
      - name: Install node dependencies
        run: npm ci
      - name: Run tests
        run: grunt test
