name: Zola

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout zola
        uses: actions/checkout@v3
        with:
          repository: getzola/zola
          submodules: true
      - name: Install rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -y | sh
          rustup target add aarch64-unknown-linux-gnu
      - name: Install dependencies
        run: sudo apt-get -y install --no-install-recommends gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu musl-tools
      - name: Build zola
        run: cargo build --release --target=aarch64-unknown-linux-gnu --verbose
      - name: Create package
        uses: actions/upload-artifact@v3
        with:
          name: zola-aarch64-linux
          path: "target/release/zola"
